# Site settings
title: Yurii Lahodiuk
email: yura.lagodiuk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about Algorithms, Programming Problems solving techniques and
  interesting Computer Science topics.
  Expressed opinions are my own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lagodiuk.github.io" # the base hostname & protocol for your site
twitter_username: ylahodiuk
github_username:  lagodiuk

# Build settings
markdown: kramdown
